name: bucket_release
on:
  push:
    branches:
      - master
jobs:
  bucket_release:
    runs-on: ubuntu-latest
    name: Update a Textile bucket
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    - name: Textile Bucket Push
      id: push
      uses: textileio/github-action-bucket-push@v3
      with:
        bucket-name: 'textile-js-todo-demo'
        path: 'build/*'
        token: ${{ secrets.TEXTILE_AUTH_TOKEN }}
    - name: Get the output CID
      run: echo "The CID was ${{ steps.push.outputs.cid }}"
    - name: Update DNSLink
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        RECORD_DOMAIN: 'txtl.us'
        RECORD_NAME: '_dnslink.todo'
      id: dnslink
      uses: textileio/cloudflare-update-dnslink@master
      with:
        cid: ${{ steps.push.outputs.cid }}
